src/java/com/mobizi/controller/CategoryBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobizi.controller;

import com.mobizi.dao.CategoryDao;
import com.mobizi.entity.Category;
import com.mobizi.entity.CategoryParent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author tran
 */
@ManagedBean
@SessionScoped
public class CategoryBean {

    private Category cate=new Category();
    private CategoryParent catepr=new CategoryParent();
    
    
    //find all category by id_parent
    public ArrayList<Category> getCategoriesByParent(int id_parent) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        CategoryDao dao = new CategoryDao();
        return dao.getCategory_By_Idparent(id_parent);
    }
    
    //get all parent category
    public ArrayList<CategoryParent> getAllCategoryParent() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        CategoryDao dao=new CategoryDao();
        return dao.getAll_ParentCategory();
    }
    public CategoryBean() {
    }

    public Category getCate() {
        return cate;
    }

    public void setCate(Category cate) {
        this.cate = cate;
    }

    public CategoryParent getCatepr() {
        return catepr;
    }

    public void setCatepr(CategoryParent catepr) {
        this.catepr = catepr;
    }
    
    
}

src/java/com/mobizi/controller/UserBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobizi.controller;

import com.mobizi.dao.UserDao;
import com.mobizi.entity.User;
import java.io.IOException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.servlet.http.Part;

/**
 *
 * @author tran
 */
@ManagedBean
@SessionScoped
public class UserBean {

    private Part file;
    private static final String addressPathMem ="E:\\JAVA PROJECT\\mobizi\\web\\resources\\default\\img\\img_members\\";
    private  User user=new User();
    private String picturechange;
    private String passwordnew;
    private String passwordold;
    private String passwordconfirm;
    private String error_old;
    private String error_new;
    private String error_confirm;
    private String error;
    private String errori;
    private String messagep;
    private String messagei;
    private String messageimage;
    private String[] errors;
    public UserBean() {
    }
    
     //check username
    public boolean checkLogin()
            throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        User item = getUser_by_username(user.getUsername());
        if (item.getUsername() != null && item.getPassword().equals(user.getPassword())) {
            return true;
        }
        return false;
    }

    //get user by username
    public User getUser_by_username(String username) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        UserDao dao = new UserDao();
        return dao.getUser_by_username(username);
    }
    //get all user
    public ArrayList<User> getAll_User() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        UserDao dao=new UserDao();
        return dao.getAll_user();
    }
    
    //delete user
    public void delete_User_By_ID() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String userID = request.getParameter("id");
        UserDao dao=new UserDao();
        dao.delete_User_By_ID(Integer.parseInt(userID));
    }
    
    //banned user by id
    public void banned_User_BY_ID() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String userID = request.getParameter("id");
        UserDao dao=new UserDao();
        dao.banned_User_By_ID(Integer.parseInt(userID));
    }
    // login
    public String login() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {

        if (checkLogin()) {
            if( getUser_by_username(user.getUsername()).getStatus().equalsIgnoreCase("baned")==false){
                HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
                User entity = getUser_by_username(user.getUsername());
                session.setAttribute("id_user",entity.getId_user());//kiem tra lai???
                session.setAttribute("username", entity.getUsername());
                session.setAttribute("role", entity.getRole());
                error="";
                user.setMail(entity.getMail());
                user.setAddress(entity.getAddress());
                user.setBirthday(entity.getBirthday());
                user.setCity(entity.getCity());
                user.setFull_name(entity.getFull_name());
                user.setGender(entity.getGender());
                user.setLast_access_date(entity.getLast_access_date());
                user.setPicture(entity.getPicture());
                user.setTel(entity.getTel());
                user.setRole(entity.getRole());
                user.setUsername(entity.getUsername());
                user.setStatus(entity.getStatus()); 
                if(checkRole()){
                    return "admin/admin_page?faces-redirect=true";
                }else{
                    return "homepage_1?faces-redirect=true";
                }
            }else {
                return "isbanned?faces-redirect=true";
            }
        }else {
                error = "Error: Username or password is wrong";
                return "login?faces-redirect=true";
        }
    }
    //log out
    public String logout() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        session.removeAttribute("username");
        session.removeAttribute("id_user");
        session.removeAttribute("role");
        user.setUsername(null);
        UserBean use=new UserBean();
        use.setMessagei("");
        use.setMessageimage("");
        use.setMessagep("");
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "homepage_1?faces-redirect=true";
    }
      
    //check session - true:  logined
    public boolean checkSession() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (session.getAttribute("username") == null) {
            return false;
        } else {
            return true;
        }
    }
    
    //check role
    public boolean checkRole(){
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if ((Integer) session.getAttribute("role") == 1) {
            return true;// is admin
        }else {
            return  false;// is member
        }
        
    }
    
    //to display member or admin
    public String checkType(){
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if ((Integer) session.getAttribute("role") == 1) {
            return "Administrator";
        }else {
            return  "Member";
        }
    }
    //check null
    public boolean checkNull(String item){
//        return item!="";
        return !item.equalsIgnoreCase("");
    }
    //update info
    public void update_Info() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        Integer id_user=(Integer) session.getAttribute("id_user");
        UserDao dao=new UserDao();
        errori="";
        messagei="";
        if(checkNull(user.getFull_name())&&checkNull(user.getMail())&&checkNull(user.getCity())
                &&checkNull(user.getGender())&&checkNull(user.getTel())&&checkNull(user.getAddress())){
            dao.update_Info(id_user,user.getFull_name(), user.getMail(),user.getTel(), user.getCity(), user.getAddress(), user.getGender());
            messagei="Change info success";
            errori="";
        }else errori="Điền đầy đủ vào form";
    }
    
    //check password
    
    
    //check not null
    public boolean checkPassword(String pas){
//        return pas!="";
        return !pas.equalsIgnoreCase("");
    }
    
    //change password
    public void change_Password() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        String userName=(String) session.getAttribute("username");
        User entity=findUser_by_Username(userName);
        UserDao dao=new UserDao();
        error="";
        error_old="";
        error_new="";
        error_confirm="";
        messagep="";
        if(checkPassword(passwordold)&&checkPassword(passwordnew)&&checkPassword(passwordconfirm)){
            if( !entity.getPassword().equalsIgnoreCase(passwordold)){
                error_old="Password cũ sai,mời nhập lại";
            }
            if(passwordnew.length()<6){
                    error_new="Password phải nhiều hơn 6 kí tự ";
            }
            if(!passwordnew.equalsIgnoreCase(passwordconfirm)){
                        error_confirm="Phải nhập đúng password mới";
            }
        }else{
            error="Password không được rỗng";
        }
        if(error==""&&error_old==""&&error_new==""&error_confirm==""){
            dao.changePassword(passwordnew, entity.getId_user());
            error="";
            messagep="change password success";
        }
        
    }
    //change avatar
    public void changeAvatar() throws IOException, SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        String userName=(String) session.getAttribute("username");
        String picture_old=findUser_by_Username(userName).getPicture();
        ImageBean image = new ImageBean();
        image.changeAvatar(getFile(), addressPathMem, userName,picture_old);
        user.setPicture(findUser_by_Username(userName).getPicture());
        messageimage = "Upload Image and Change Avatar successfully!";
        
    }

    //get user by id
    public User findUser_by_Username(String username) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException{
        UserDao dao=new UserDao();
        return dao.getUser_by_username(username);
    }
    
     // login

web/views/admin/components/changeImageProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form enctype="multipart/form-data">

                <div class=" col-md-12 well">
                    <div class="col-md-12 text-left" style="margin-bottom: 10px;">
                        <div class="col-md-6"><strong>Chọn sản phẩm</strong></div>
                        <div class="col-md-offset-8 "><strong>Ảnh cũ</strong></div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6 no_padding" id="cate1">
                            <h:selectOneMenu id="parent" value="#{productBean.name}" class="form-control product-type">
                                <!--<f:selectItem itemValue="0" itemLabel="Select" />-->
                                <f:selectItem itemValue="" itemLabel="-- Product --" itemDisabled=""/>
                                <f:selectItems value="#{productBean.allProduct}" var="item"
                                               itemLabel="#{item.name}" itemValue="#{item.name}">
                                </f:selectItems>
                                <f:ajax execute="parent" render="son" listener="#{productBean.getImageAjax}"/>
                            </h:selectOneMenu>
                        </div>
                        <div class="col-md-6">
                            <h:graphicImage  id="son" value="http://localhost:8084/mobizi/faces/resources/default/img/img_system/img_thumbnail/#{productBean.imageajax}"/>

                        </div>
                    </div>
                    <div class="col-md-12" >
                        <div class="col-md-12 text-left">Chọn ảnh mới: </div>
                        <div class="col-md-12">
                        <h:inputFile class="col-md-offset-3 col-md-6" style="width: 50%;margin: 10px 0px; "
                                     value="#{productBean.file}"/>
                        </div>
                        <div class="col-md-12">
                            <h:commandButton class="btn btn-default left" value="Change Image" 
                                         action="#{productBean.changePicture}"/>
                        </div>
                    </div>
                    <h5 style="color: #999900;"><i>#{productBean.messimgproduct}</i></h5>
                </div>
                
            </h:form>
        </ui:composition>
    </h:body>
</html>

web/views/admin/components/changePicture.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form enctype="multipart/form-data">

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-6 well">
                        <div class="col-md-12">
                            <img src="http://localhost:8084/mobizi/faces/resources/default/img/img_members/#{userBean.picture}"
                             height="200" width="200" class="img-circle"/>
                        </div>
                        <div class="col-md-12" >
                            <h:inputFile class="col-md-offset-3 col-md-6" style="width: 50%;margin: 30px 0px; "
                                         value="#{userBean.file}"/>
                        </div>
                        <div class="form-group text-center">
                            <h:commandButton class="btn btn-default" value="Change Avatar" 
                                             action="#{userBean.changeAvatar()}"/>
                        </div>
                        <h5 style="color: #999900;"><i>#{userBean.messageimage}</i></h5>
                    </div>
                </div>
            </h:form>
        </ui:composition>
    </h:body>
</html>

web/views/admin/components/change_password.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form>
                <div class="well col-md-offset-2 col-md-6">
                    <legend style="text-align: center">Change password</legend>

                    <div class="form-group">
                        <label class="control-label" for="password">Password Old</label>
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <h:inputSecret value="#{userBean.passwordold}" pt:placeholder="Password" class="form-control"/>

                        </div>
                        <span style="color: red">#{userBean.error_old}</span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="password">Password New</label>
                        <p style="color: gainsboro">(Must be than 6 character)</p>
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <h:inputSecret value="#{userBean.passwordnew}" pt:placeholder="New Password" class="form-control"/>
                        </div>
                    </div>
                    <span style="color: red">#{userBean.error_new}</span>
                    <div class="form-group">
                        <label class="control-label" for="password">Confirm password</label>
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <h:inputSecret value="#{userBean.passwordconfirm}" pt:placeholder="Re-Password" class="form-control"/>
                        </div>
                        <span style="color: red">#{userBean.error_confirm}</span>
                    </div>
                    <div class="form-group text-center">
                        <h:commandButton class="btn btn-success" value="Ok"
                                         action="#{userBean.change_Password()}">
                        </h:commandButton>
                    </div>
                    <h5 style="color: green;"><i>#{userBean.messagep}</i></h5>
                    <h5 style="color: red;"><i>#{userBean.error}</i></h5>
                </div>
            </h:form>
        </ui:composition>
    </h:body>
</html>

web/views/admin/components/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form enctype="multipart/form-data">
                <div class="col-md-12 text-left">
                    <h1 class="text-center">
                        Create new Product
                    </h1>
                    <div class="col-md-12 text-left">
                        <div class="edit">
                            <fieldset>
                                <div class="col-md-12 form-group margin50">
                                    <label class="col-md-2" for="name1">Name</label>
                                    <div class="col-md-8">
                                        <h:inputText  id="name1" value="#{productBean.name}" pt:placeholder="Name product" class="form-control "/>
                                    </div>
                                </div>
                                <div class=" col-md-12 form-group">
                                    <label class="col-md-2" for="cate1">Category</label>
                                    <div class="col-md-8">
                                        <div class="col-md-6 no_padding" id="cate1">
                                            <h:selectOneMenu id="parent" value="#{productBean.id_parent}" class="form-control product-type">
                                                <!--<f:selectItem itemValue="0" itemLabel="Select" />-->
                                                <f:selectItem itemValue="" itemLabel="-- Type --" itemDisabled=""/>
                                                <f:selectItems value="#{categoryBean.allCategoryParent}" var="item"
                                                               itemLabel="#{item.name}" itemValue="#{item.id}">
                                                </f:selectItems>
                                                <f:ajax execute="parent" render="son" listener="#{productBean.getCategoryAjax}"/>
                                            </h:selectOneMenu>
                                        </div>
                                        <div class="col-md-6">
                                            
                                            <h:selectOneMenu id="son" class="form-control" value="#{productBean.category_id}">
                                                <f:selectItem itemValue="" itemLabel="---- Category ----" itemDisabled=""/>
                                                <f:selectItems value="#{productBean.listcategory}" var="item1"
                                                               itemValue="#{item1.id_category}" itemLabel="#{item1.name}"/>
                                            </h:selectOneMenu>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group ">
                                    <label class="col-md-2"  for="price1">Price</label>
                                    <div class="col-md-8">
                                        <h:inputText  id="price1" value="#{productBean.price}" pt:placeholder="#{it.price}" class="form-control "/>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group ">
                                    <label class="col-md-2"  for="promotion1">Promotion</label>
                                    <div class="col-md-8">
                                        <h:inputText  id="promotion1" value="#{productBean.price_promotion}" pt:placeholder="#{it.price_promotion}" class="form-control "/>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group ">
                                    <label class="col-md-2"  for="quantity1">Quantity</label>
                                    <div class="col-md-8">
                                        <h:inputText  id="quantity1" value="#{productBean.quantity}" pt:placeholder="#{it.quantity}" class="form-control "/>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label class="col-md-2" for="manufacturer1">Manufacturer</label>
                                    <div class="col-md-8">
                                        <h:inputText id="manufacturer1" value="#{productBean.manufacter}" pt:placeholder="#{it.manufacter}" class="form-control "/>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label class="col-md-2" for="show">Show/Hide</label>
                                    <div class="col-md-4">
                                        <h:selectOneMenu value="#{productBean.hide}" class="form-control product-type">
                                            <f:selectItem itemValue="0" itemLabel="Select" itemDisabled="true"/>
                                            <f:selectItem itemValue="1" itemLabel="Hide"/>
                                            <f:selectItem itemValue="2" itemLabel="Show"/>
                                            <f:selectItem itemValue="3" itemLabel="Show first"/>
                                        </h:selectOneMenu>
                                    </div>
                                    <div class="col-md-4">
                                        <ul>
                                            <li>Notice :</li>
                                            <li>1 = hide for all user</li>
                                            <li>2 = show for user</li>
                                            <li>3 = show in homepage</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <h:inputFile value="#{productBean.file}"/>
                                    <p>* Only image type : JPEG,JPG,PNG </p>
                                </div>

                                <h:commandButton value="Submit" action="#{productBean.insertNew_Product()}" class="col-md-offset-5" style="margin-bottom: 20px;">
                                    <!--<f:param name="id" value="{it.id_product}"/>-->
                                </h:commandButton>

                            </fieldset>

                        </div>
                    </div>
                </div>
            </h:form>
        </ui:composition>
    </h:body>
</html>

web/views/admin/components/manage_member.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <link rel="stylesheet" href="../../resources/custom/style1.css"/>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form>
                <div class="col-md-12 text-left" style="margin-bottom: 30px;">
                    <h1 class="text-center">
                        Manage User
                    </h1>
                    
                </div>
                <div id="no-more-tables" class="text-left">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <tbody>
                            <tr>
                                <th class="numeric">ID</th>
                                <th class="numeric">Full name</th>
                                <th class="numeric">Username</th>
                                <th class="numeric">Email</th>
                                <th class="numeric">Address</th>
                                <th class="numeric">Tel</th>
                                <th class="numeric">Tel</th>
                                <th class="numeric">Action</th>                                                                                       
                            </tr>                                                                        
                            <ui:repeat value="#{userBean.all_User}" var="item">
                                <tr >
                                    <td data-title="ID">#{item.id_user}</td>
                                    <td data-title="Full name">#{item.full_name}</td>
                                    <td data-title="Username" class="numeric">#{item.username}</td>
                                    <td data-title="Email" class="numeric">#{item.mail}</td>
                                    <td data-title="Address" class="numeric">#{item.address}</td>
                                    <td data-title="Tel" class="numeric">#{item.tel}</td>
                                    <td data-title="Tel" class="numeric">#{item.status}</td>
                                    <td data-title="Action" class="numeric">
                                        <h:commandButton action="#{userBean.delete_User_By_ID()}" value="delete">
                                            <f:param name="id" value="#{item.id_user}"/>
                                        </h:commandButton>
                                        <h:commandButton action="#{userBean.banned_User_BY_ID()}" value="banned">
                                            <f:param name="id" value="#{item.id_user}" />
                                        </h:commandButton>
                                    </td>
                                </tr>
                            </ui:repeat>                                       
                        </tbody>
                    </table>
                </div>
            </h:form>
        </ui:composition>
    </h:body>
</html>