src/java/com/mobizi/controller/CartBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobizi.controller;

import com.mobizi.dao.ProductDao;
import com.mobizi.entity.Product;
import com.mobizi.entity.SubProduct;
import com.mobizi.entity.User;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import com.sun.faces.el.ELConstants;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.faces.event.AjaxBehaviorEvent;

/**
 *
 * @author tran
 */
@ManagedBean
@RequestScoped
public class CartBean {

    private Product product;
    private ArrayList<Product> cartlist;
    private Long total;
    private Integer size;
    private User user=new User();
    
    public CartBean() {
    }
    

// get product by id
    public Product getProduct_by_ID(Integer id_product) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        ProductDao dao = new ProductDao();
        return dao.getProduct_by_id(id_product);

    }

// add item to cart in page detail product
    public String addCart()throws IOException, ServletException, SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        HttpServletResponse response = (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
// First get the item values from the request.
        String productID = request.getParameter("id");
// Now create an item to add to the cart.
        Product item = getProduct_by_ID(Integer.parseInt(productID));
        HttpSession session = request.getSession();
// Get the cart.
        ArrayList<Product> cart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        Boolean has=false;
// If there is no shopping cart, create one.
        if (cart == null) {
            cart = new ArrayList<>();            
            session.setAttribute("ShoppingCart", cart);         
        }
        Integer index=0;
        for (Integer k=0; k< cart.size(); k++) {
            if (cart.get(k).getId_product()==Integer.parseInt(productID))
                   {
                has = true;
                index=k;
                break;
            }           
        }
        if(cart.size()<10){
            if (!has) {
                item.setQuantity(1);
                item.setTemp(item.getQuantity()*item.getPrice());
                cart.add(item);
            }else{
                Integer n=cart.get(index).getQuantity();
                Long t=cart.get(index).getPrice();
                cart.get(index).setQuantity(n+1);
                cart.get(index).setTemp((n+1)*t);
            }
        }
        session.setAttribute("ShoppingCart", cart);//moi them
        
        return "homepage_1?faces-redirect=true";
    }
    
    
    //increase quantity of product in cart
    public void plusQuantity(Product product){
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
//        String productID = request.getParameter("id_product");
        HttpSession session = request.getSession();
//        product.getId_product();
        ArrayList<Product> cart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        
        for (Product p : cart) {
            if (p.getId_product()==product.getId_product()){
                if(p.getQuantity()<10){                   
                p.setQuantity(p.getQuantity() + 1);
                p.setTemp(p.getQuantity()*p.getPrice());
                p.setIntroduce(null);
                break;
            }   else p.setIntroduce("SL < 10");          
        }
        }
        
         
        session.setAttribute("ShoppingCart", cart);
        
    }
    
    //decrease quantity of product in cart
    public void subQuantity(Product product){
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
//        String productID = request.getParameter("id_product");
        HttpSession session = request.getSession(); 
//        product.getId_product();
        ArrayList<Product> cart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        for (Product p : cart) {
            if (p.getId_product()==product.getId_product()){
                if(p.getQuantity()>1){
                p.setQuantity(p.getQuantity() - 1);
                p.setTemp(p.getQuantity()*p.getPrice());
                p.setIntroduce("");
                break;
                }else p.setIntroduce("SL > 0");            
        }
        }
        
        session.setAttribute("ShoppingCart", cart);
        
    }
    
// delete item in cart
    public String deleteItem_in_Cart(){
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String productID = request.getParameter("id_product");
        HttpSession session = request.getSession();
        ArrayList<Product> shoppingCart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        int index = -1;
        for (Integer k=0; k< shoppingCart.size(); k++) {
            if (shoppingCart.get(k).getId_product()==Integer.parseInt(productID)) {
                index = k;
                break;
            }
        }
        if (index != -1) {
            shoppingCart.remove(index);
            session.setAttribute("ShoppingCart", shoppingCart);  
        }
        return "cart?faces-redirect=true";
    }
    
    //ajax tinh sum
    public void countSummary(AjaxBehaviorEvent event){
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        ArrayList<Product> listcart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
         total=0l;
        for(Product p: listcart){
            total += p.getTemp();
        }
//        total=total1;
    }
// get item in cart    
    public Product getCart_item(Integer id_product){
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        ArrayList<Product> cart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String productID = request.getParameter("id");
        for (Integer k=0; k< cart.size(); k++) {
            if (cart.get(k).getId_product()==Integer.parseInt(productID)){
                return cart.get(k);                
            }            
        }
        return null;
    }
    
// get list cart    
    public ArrayList<Product> getListCart() {
        ArrayList<Product> list = new ArrayList<>();
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        return list = (ArrayList<Product>) session.getAttribute("ShoppingCart");
    }

// get size cart to display number product in giỏ hàng
    public Integer getSizeCart(){
      
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        ArrayList<Product> listcart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        if (listcart == null) {
            listcart = new ArrayList<>();            
            session.setAttribute("ShoppingCart", listcart);         
        }
//        Integer number;
//        number=listcart.size();
        return listcart.size();
    }
    
    //insert to cart when click on button "MUA"
     public String insertCart()throws IOException, ServletException, SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        HttpServletRequest request=(HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
// First get the item values from the request.
        String productID = request.getParameter("id");
// Now create an item to add to the cart.
        Product item = getProduct_by_ID(Integer.parseInt(productID));
        HttpSession session = request.getSession();
// Get the cart.
        ArrayList<Product> cart = (ArrayList<Product>) session.getAttribute("ShoppingCart");
        Boolean has=false;
// If there is no shopping cart, create one.
        if (cart == null) {
            cart = new ArrayList<>();            
            session.setAttribute("ShoppingCart", cart);         
        }
        Integer index=0;
        for (Integer k=0; k< cart.size(); k++) {
            if (cart.get(k).getId_product()==Integer.parseInt(productID))
                   {
                has = true;
                index=k;
                break;
            }           
        }
        if(cart.size()<10){
            if (!has) {
                item.setQuantity(1);
                item.setTemp(item.getQuantity()*item.getPrice());
                cart.add(item);
            }else{
                Integer n=cart.get(index).getQuantity();
                Long t=cart.get(index).getPrice();
                cart.get(index).setQuantity(n+1);
                cart.get(index).setTemp((n+1)*t);
            }
        }
        cartlist=cart;
        session.setAttribute("ShoppingCart", cart);   
        
        return "cart?faces-redirect=true";
    }
        
   

// SET & GET
    

src/java/com/mobizi/controller/RegisterBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobizi.controller;

import com.mobizi.dao.UserDao;
import com.mobizi.entity.User;
import java.sql.SQLException;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import org.apache.tomcat.dbcp.pool2.PoolUtils;

/**
 *
 * @author tran
 */
@ManagedBean
@RequestScoped
public class RegisterBean {

    private User user = new User();
    private String erros;
    private String erros1;
    private String erros2;
    private String errornull;
    private String password1;

    public RegisterBean() {

    }

    public String register() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        UserDao dao = new UserDao();
        erros = null;
        erros1 = null;
        erros2=null;
        errornull=null;
        if( !user.getUsername().equalsIgnoreCase("") && !user.getPassword().equalsIgnoreCase("") && !user.getMail().equalsIgnoreCase("") && !password1.equalsIgnoreCase("")){
            
            User item = getUser_by_username(user.getUsername());
            User item1 = getUser_by_Mail(user.getMail());

            if (item.getUsername() != null) {
                erros = "username da ton tai";
                
            }
            if (!user.getPassword().equals(password1)) {
                erros1 = "Password phai giong nhau";
            }
            if (item1.getMail()!=null) {
                erros2="Email nay da ton tai";
            }
            if(erros==null && erros1==null && erros2==null ){
                dao.addUser(user.getUsername(), user.getPassword(), user.getMail());
                erros = "";
                erros1 = "";
                erros2 = "";
                return "login?faces-redirect=true";
            }
            return null;
        }else{
           errornull="Điền đầy đủ vào form ";
            return null;
        }
    }

    //get user by username
    public User getUser_by_username(String username) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        UserDao dao = new UserDao();
        return dao.getUser_by_username(username);
    }
//get user by mail

    public User getUser_by_Mail(String mail) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        UserDao dao = new UserDao();
        return dao.getUser_by_Mail(mail);
    }

    //SET GET
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getErros() {
        return erros;
    }

    public void setErros(String erros) {
        this.erros = erros;
    }

    public String getErros1() {
        return erros1;
    }

    public void setErros1(String erros1) {
        this.erros1 = erros1;
    }

    public String getErros2() {
        return erros2;
    }

    public void setErros2(String erros2) {
        this.erros2 = erros2;
    }

    public String getErrornull() {
        return errornull;
    }

    public void setErrornull(String errornull) {
        this.errornull = errornull;
    }
    

    
    public String getPassword1() {
        return password1;
    }

    public void setPassword1(String password1) {
        this.password1 = password1;
    }

    public Integer getId_user() {
        return user.getId_user();
    }

    public void setId_user(Integer id_user) {
        user.setId_user(id_user);
    }

    public String getMail() {
        return user.getMail();
    }

    public void setMail(String mail) {
        user.setMail(mail);
    }

    public String getPassword() {
        return user.getPassword();
    }

    public void setPassword(String password) {
        user.setPassword(password);
    }

    public String getUsername() {
        return user.getUsername();
    }

    public void setUsername(String username) {
        user.setUsername(username);
    }

    public Date getBirthday() {
        return user.getBirthday();
    }

    public void setBirthday(Date birthday) {
        user.setBirthday(birthday);
    }

    public String getTel() {
        return user.getTel();
    }

    public void setTel(String tel) {
        user.setTel(tel);
    }

    public String getStatus() {
        return user.getStatus();
    }

    public void setStatus(String status) {
        user.setStatus(status);
    }

    public String getPicture() {
        return user.getPicture();
    }

    public void setPicture(String picture) {
        user.setPicture(picture);
    }

    public Date getLast_access_date() {
        return user.getLast_access_date();
    }

    public void setLast_access_date(Date last_access_date) {
        user.setLast_access_date(last_access_date);
    }

    

    public String getCity() {
        return user.getCity();
    }

    public void setCity(String city) {
        user.setCity(city);
    }

    public String getAddress() {
        return user.getAddress();
    }

    public void setAddress(String address) {
        user.setAddress(address);
    }

    public String getGender() {
        return user.getGender();
    }

    public void setGender(String gender) {
        user.setGender(gender);
    }

    

    public Integer getRole() {
        return user.getRole();
    }

    public void setRole(Integer role) {
        user.setRole(role);
    }

}

web/views/cart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="../resources/default/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="../resources/custom/css_homepage_1.css" type="text/css"/>  
        <title>:: Mobizi Mobile &amp; Computer :: | Mobizi.vn</title>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
        <script src="../resources/default/jquery/jquery-1.11.3.min.js"></script>
        <script src="../resources/default/js/bootstrap.min.js"></script>
    </h:head>
    <h:body style="background: #f9f9f9">  

        <ui:composition template="../common/template_product/temp.xhtml">
            <ui:define name="header">
                <ui:include src="../common/template_product/header.xhtml"></ui:include>
            </ui:define>
            <ui:define name="content">
                <h:form id="myform">
                    <div class="container">
                        <div class="row">
                            <div class="home_title no_padding col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                                <div class="new_product_title" >Giỏ hàng - Đặt hàng trực tuyến</div>
                                <div class="new_product_title_line no_padding" ></div>
                            </div>
                        </div>
                        <table width="100%" class="yourcart_table row">
                            <tbody>
                                <tr class="yourcart_table_header" >
                                    <td>Hình ảnh</td>
                                    <td>Tên sản phẩm</td>
                                    <td class="hidden-xs">Đơn giá</td>
                                    <td>Số lượng</td>
                                    <td class="hidden-xs">Thành tiền</td>
                                    <td class="hidden-xs" width="30">Xóa</td>
                                </tr>
                                <ui:repeat id="cartid" value="#{cartBean.listCart}" var="item">
                                    <tr>
                                        <td class="product_img_td">
                                            <div class="td_product_img">
                                                <img  src="../resources/default/img/img_system/img_thumbnail/#{item.mainImageURL}"/>
                                            </div>
                                        </td>
                                        <td class="product_name_td">
                                            <p class="cart_item_name product_name2 yourcart">#{item.name}</p>
                                        </td>
                                        <td class="td_price hidden-xs" align="right">#{item.price} VNĐ </td>
                                        <td class="td_num">
                                            <h:commandButton  class="sub_num_btn" id="link1" >
                                                <f:ajax event="click" listener="#{cartBean.subQuantity(item)}"  render="pd sum noti total"/>
                                            </h:commandButton>
                                            <h:outputText  class="tx_num"  id="pd" value="#{item.quantity}"/>
                                            <h:commandButton class="add_num_btn" id="link2" action="#{cartBean.plusQuantity()}">
                                                <f:ajax event="click" listener="#{cartBean.plusQuantity(item)}"  render="pd sum noti total"/>
                                            </h:commandButton>
                                            <div id="#{item.id_product}" style="margin-top: 20px;">
                                                <h:outputText id="noti" value="#{item.introduce}"/></div>
                                        </td>
                                        <td class="td_sum hidden-xs" align="right"><h:outputText id="sum" value="#{item.temp}"/> VNĐ </td>
                                        <td class="">
                                            <h:commandButton  id="link" class="btn btn-default" action="#{cartBean.deleteItem_in_Cart()}" value="xóa">
                                                <f:param name="id_product" value="#{item.id_product}"/>
                                            </h:commandButton>
                                        </td>
                                    </tr>
                                </ui:repeat>
                                <tr class="yourcart_table_footer hidden-xs">
                                    <td colspan="3" class="td_total_title">Tổng cộng</td>
                                    <td class="td_total" colspan="3">
                                        <h:outputText id="total" value="#{cartBean.total}"/> VNĐ</td>
                                </tr>
                                <h:commandButton id="changeme" style="display:none">
                                    <f:ajax execute="@this" listener="#{cartBean.countSummary}" render="total" ></f:ajax>
                                </h:commandButton>
                            </tbody> 
                        </table>
                        <div class="row">
                            <div class="home_title no_padding col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="new_product_title">
                                    <div class="product_title">Thông tin đặt hàng</div>
                                </div>
                                <div class="new_product_title_line"></div>
                            </div>
                        </div>
                    </div>
                    <div class="" >
                        <a href="#header" class="totop">
                        <span class="glyphicon glyphicon-arrow-up" ></span>
                        TOP</a>
                    </div>
                </h:form>
                <h:form>
                    <div class="container">
                        <div class="row">              
                            <div class="contact_form shopping_cart no_padding col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                <div class="contact_form_content_bg">                                      
                                    <div class="contact_txt_bg">

                                        <h:inputText  id="txt_contact_name" class="contact_txt" pt:placeholder="Họ và tên" value="#{orderBean.receiver}"/><label id="name_error_mes"></label>
                                    </div>
                                    <div class="contact_txt_bg">

                                        <h:inputText id="txt_contact_email" class="contact_txt" pt:placeholder="Email" value="#{orderBean.mail}"/><label id="email_error_mes"></label>
                                    </div>
                                    <div class="contact_txt_bg">

                                        <h:inputText  id="txt_contact_address" class="contact_txt" pt:placeholder="Địa chỉ" value="#{orderBean.address_order}"/><label id="address_error_mes"></label>
                                    </div>
                                    <div class="contact_txt_bg">

                                        <h:inputText  id="txt_contact_phone" class="contact_txt" pt:placeholder="Điện thoại" value="#{orderBean.tel_receiver}"/><label id="phone_error_mes"></label>
                                    </div>                            
                                    <div class="contact_txta_bg">

                                        <h:inputTextarea id="txt_contact_content" class="contact_txta" pt:placeholder="Ghi chú" />           
                                        <label id="content_error_mes"></label>
                                    </div>            
                                </div>                      

                                <div class="contact_button">
                                    <h:commandButton action="#{orderBean.insertOrdertable()}" value="Gởi đơn đặt hàng" class="contact_button_send"></h:commandButton>

                                </div>
                                <p style="color: red;margin-top:300px;text-align:center;">#{orderBean.meserror}</p>
                            </div>
                            <div class="cart_info_bg col-lg-7 col-md-7 col-sm-7 col-xs-12">
                                <span>Cách thức mua hàng trực tuyến:</span><br/>
                                1. Khách hàng chọn sản phẩm, điền đầy đủ thông tin đặt hàng rồi gởi cho <strong>Mobizi</strong>.<br/>
                                2. <strong>Mobizi</strong> sẽ liên hệ với quý khách trong thời gian sớm nhất để xác nhận thông tin đặt hàng.<br/>
                                3. Nhân viên của <strong>Mobizi</strong> sẽ giao hàng đến tận nơi và nhận thanh toán khi giao hàng.<br/>
                                <div class="note_bg">
                                    <strong class="note">Lưu ý:</strong> <strong>Mobizi</strong> chỉ chấp nhận những đơn đặt hàng cung cấp thông tin chính xác về địa chỉ, số điện thoại, email. <strong>Mobizi</strong> cam kết tất cả hàng hóa gởi đến quý khách đều là hàng mới 100%.
                                </div>
                                <div class="shopping_img">
                                    <img src="../../resources/default/img/img_system/shopping.gif"/>
                                </div>                                                                               
                            </div>           
                        </div>
                        <div style="margin-top: 50px;"></div>
                    </div>
                </h:form>
                <script>
                    $(document).ready(function (){
                        document.getElementById("myform:changeme").click();
                    });
                    $(".td_num input").on('click',function (){
                        document.getElementById("myform:changeme").click();
                    });
                </script> 
            </ui:define>
            <ui:define name="footer">
                <ui:include src="../common/template_product/footer.xhtml"></ui:include>
            </ui:define>
        </ui:composition>

    </h:body>
</html>

web/views/change_avatar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Change avatar</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/default/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/custom/list_table_style.css" type="text/css"/>  
        <!--<title>:: Mobizi Mobile &amp; Computer :: | Mobizi.vn</title>-->
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
        <script src="http://localhost:8084/mobizi/faces/resources/default/jquery/jquery-1.11.3.min.js"></script>
        <script src="http://localhost:8084/mobizi/faces/resources/default/js/bootstrap.min.js"></script>
    </h:head>
    <h:body>
        <ui:composition template="../common/template_member/member_page_template.xhtml">
            <ui:define name="content">
                
                    <ui:include src="admin/components/changePicture.xhtml"></ui:include>
                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/views/change_password.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Change password</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/default/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/custom/list_table_style.css" type="text/css"/>  
        <!--<title>:: Mobizi Mobile &amp; Computer :: | Mobizi.vn</title>-->
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
        <script src="http://localhost:8084/mobizi/faces/resources/default/jquery/jquery-1.11.3.min.js"></script>
        <script src="http://localhost:8084/mobizi/faces/resources/default/js/bootstrap.min.js"></script>
    </h:head>
    <h:body>
        <ui:composition template="../common/template_member/member_page_template.xhtml">
            <ui:define name="content">
                
                    <ui:include src="admin/components/change_password.xhtml"></ui:include>
                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/views/change_profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Change info</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/default/css/bootstrap.min.css"/>
        <script src="http://localhost:8084/mobizi/faces/resources/default/jquery/jquery-1.11.3.min.js"></script>
        <script src="http://localhost:8084/mobizi/faces/resources/default/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="http://localhost:8084/mobizi/faces/resources/custom/style1.css"/>
        
    </h:head>
    <h:body>
        <ui:composition template="../common/template_member/member_page_template.xhtml">
            <ui:define name="content">
                <ui:include src="admin/components/change_profile.xhtml"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/views/newjsf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Test Ajax</title>
    </h:head>
    <h:body>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputText value="ID: "/>
                <h:inputText id="inputID" value="#{userBean.id}" >
                    <f:ajax event="keyup" render="inputName" execute="@this" />
                </h:inputText>
                <h:outputText value="Name: "/>
                <h:inputText id="inputName" value="#{userBean.name}"/>
                <!-- sử dụng cái này để hiển thị tổng giá tiền-->
            </h:panelGrid>
        </h:form>
    </h:body>
</html>